### ISSUE TITLE
Compilation fails in Elixir 1.8

### ISSUE THREAD

**Issue by mhakeem** [matehat/cqex#33]
Environemnt info:
```
Erlang: 21
Elixir: 1.8.1
OS: macOS High Sierra (10.13.6)
cqex: 0.2.0
```

I was trying out your library & it won't compile. I did `mix clean`, `mix deps.clean cqex`,  then `mix deps.compile cqex` and I get the same error every time. I also tried out your other library `cqerl` which always times out and never connects to my Cassandra cluster. Not sure if this problem is also causing `cqex` to break, but it seems that this library needs to be updated to work with Elixir 1.8.

```shell
iex -S mix
Erlang/OTP 21 [erts-10.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

warning: variable "description" does not exist and is being expanded to "description()", please use parentheses to remove the ambiguity or change the variable name
  /Users/mhakeem/Documents/codes/elixir/cassandra/example/deps/cqex/mix.exs:10

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /Users/mhakeem/Documents/codes/elixir/cassandra/example/deps/cqex/mix.exs:11

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /Users/mhakeem/Documents/codes/elixir/cassandra/example/deps/cqex/mix.exs:13

==> cqex
Compiling 6 files (.ex)
warning: variable "args" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/cqex/helpers.ex:19

warning: unused import CQEx.Helpers
  lib/cqex/cluster.ex:2


== Compilation error in file lib/cqex/client.ex ==
** (ArgumentError) argument error
    :erlang.length(nil)
    expanding macro: CQEx.Helpers.defbang/1
    lib/cqex/client.ex:17: CQEx.Client (module)
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
could not compile dependency :cqex, "mix compile" failed. You can recompile this dependency with "mix deps.compile cqex", update it with "mix deps.update cqex" or clean it with "mix deps.clean cqex"
```

**Comment by matehat** [comment]
Should work now
